package com.mlpr.bankmanagementsystem;

import java.awt.Color;

public class BankForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BankForm.class.getName());

    private LoginForm loginForm;
    private BankSystem bank = BankSystem.getInstance();
    /**
     * Creates new form BankForm
     */
    public BankForm(LoginForm loginForm, String username) {
        initComponents();
        System.out.println("CUSTOMER LOGGED IN AS " + username);
        
        btnDeposit.setBackground(Color.ORANGE);
        btnWithdraw.setBackground(Color.WHITE);
        btnViewBalance.setBackground(Color.WHITE);
        btnViewAccount.setBackground(Color.WHITE);
        
        DepositPanel.setEnabled(true);
        
        this.setVisible(true);
        
        this.loginForm = loginForm;
    }
    
    public BankForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnViewAccount = new javax.swing.JButton();
        btnViewBalance = new javax.swing.JButton();
        DepositPanel = new javax.swing.JPanel();
        lblAdminPanel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblAdminPanel1 = new javax.swing.JLabel();
        btnDepositBalance = new javax.swing.JButton();
        lblAdminPanel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\rick\\Desktop\\BankLogo6.png")); // NOI18N

        btnDeposit.setBackground(java.awt.Color.orange);
        btnDeposit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnViewAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewAccount.setText("View Account Info");
        btnViewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccountActionPerformed(evt);
            }
        });

        btnViewBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewBalance.setText("View Balance");
        btnViewBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBalanceActionPerformed(evt);
            }
        });

        DepositPanel.setBackground(new java.awt.Color(204, 204, 204));
        DepositPanel.setEnabled(false);
        DepositPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdminPanel.setBackground(new java.awt.Color(255, 204, 0));
        lblAdminPanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAdminPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminPanel.setText("Enter Amount:");
        DepositPanel.add(lblAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 224, 405, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        DepositPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 262, 237, 40));

        lblAdminPanel1.setBackground(new java.awt.Color(255, 204, 0));
        lblAdminPanel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblAdminPanel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminPanel1.setText("DEPOSIT");
        DepositPanel.add(lblAdminPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, 405, -1));

        btnDepositBalance.setBackground(java.awt.Color.orange);
        btnDepositBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDepositBalance.setText("Deposit");
        btnDepositBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositBalanceActionPerformed(evt);
            }
        });
        DepositPanel.add(btnDepositBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 320, 200, 50));

        lblAdminPanel2.setBackground(new java.awt.Color(255, 204, 0));
        lblAdminPanel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAdminPanel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminPanel2.setText("Hello, {Full Name}");
        DepositPanel.add(lblAdminPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 405, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(DepositPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        btnDeposit.setBackground(Color.ORANGE);
        btnWithdraw.setBackground(Color.WHITE);
        btnViewBalance.setBackground(Color.WHITE);
        btnViewAccount.setBackground(Color.WHITE);
        
        DepositPanel.setEnabled(true);
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        btnWithdraw.setBackground(Color.ORANGE);
        btnDeposit.setBackground(Color.WHITE);
        btnViewBalance.setBackground(Color.WHITE);
        btnViewAccount.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        loginForm.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccountActionPerformed
        btnViewAccount.setBackground(Color.ORANGE);
        btnWithdraw.setBackground(Color.WHITE);
        btnDeposit.setBackground(Color.WHITE);
        btnViewBalance.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnViewAccountActionPerformed

    private void btnViewBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBalanceActionPerformed
        btnViewBalance.setBackground(Color.ORANGE);
        btnViewAccount.setBackground(Color.WHITE);
        btnWithdraw.setBackground(Color.WHITE);
        btnDeposit.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnViewBalanceActionPerformed

    private void btnDepositBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepositBalanceActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BankForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DepositPanel;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnDepositBalance;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewAccount;
    private javax.swing.JButton btnViewBalance;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAdminPanel;
    private javax.swing.JLabel lblAdminPanel1;
    private javax.swing.JLabel lblAdminPanel2;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
