package com.mlpr.bankmanagementsystem;

import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class BankForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BankForm.class.getName());

    private LoginForm loginForm;
    private BankSystem bank = BankSystem.getInstance();
    private Customer customer;
    private DepositForm depositForm;
    private WithdrawForm withdrawForm;
    private BalanceForm balanceForm;
    private AccountInfoForm accountInfoForm;
    
    /**
     * Creates new form BankForm
     */
    public BankForm(LoginForm loginForm, Customer customer) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Load icon
        try {
            URL iconUrl = getClass().getResource("/BankLogo4.png");
            if (iconUrl != null) {
                setIconImage(new ImageIcon(iconUrl).getImage());
            } else {
                System.err.println("Icon not found at /BankLogo4.png");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        System.out.println("CUSTOMER LOGGED IN AS " + customer.getUsername());
        
        lblFullName.setText(customer.getFullName());
        
//        btnDeposit.setBackground(Color.ORANGE);
//        btnWithdraw.setBackground(Color.WHITE);
//        btnViewBalance.setBackground(Color.WHITE);
//        btnViewAccount.setBackground(Color.WHITE);

        this.setVisible(true);
        
        this.loginForm = loginForm;
        this.customer = customer;
    }
    
    public BankForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnViewAccount = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnViewBalance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank Management System");

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log out");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnDeposit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeposit.setForeground(new java.awt.Color(0, 153, 0));
        btnDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deposit.png"))); // NOI18N
        btnDeposit.setText("Deposit");
        btnDeposit.setBorder(null);
        btnDeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankLogo6.png"))); // NOI18N

        btnViewAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewAccount.setForeground(new java.awt.Color(0, 153, 0));
        btnViewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewaccountinfo.png"))); // NOI18N
        btnViewAccount.setText("View Account Info");
        btnViewAccount.setBorder(null);
        btnViewAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccountActionPerformed(evt);
            }
        });

        btnWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnWithdraw.setForeground(new java.awt.Color(204, 0, 0));
        btnWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/withdraw.png"))); // NOI18N
        btnWithdraw.setText("Withdraw");
        btnWithdraw.setBorder(null);
        btnWithdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnViewBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewBalance.setForeground(new java.awt.Color(0, 153, 0));
        btnViewBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewbalance.png"))); // NOI18N
        btnViewBalance.setText("View Balance");
        btnViewBalance.setBorder(null);
        btnViewBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBalanceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome,");

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(0, 153, 0));
        lblFullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFullName.setText("{Full Name}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnViewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        if (depositForm != null && depositForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Deposit is already open!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (withdrawForm != null && withdrawForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Withdraw must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (accountInfoForm != null && accountInfoForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Account Info must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (balanceForm != null && balanceForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Balance must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        depositForm = new DepositForm(customer);
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        if (withdrawForm != null && withdrawForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Withdraw is already open!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (depositForm != null && depositForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Deposit must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (accountInfoForm != null && accountInfoForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Account Info must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (balanceForm != null && balanceForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Balance must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        withdrawForm = new WithdrawForm(customer);
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        loginForm.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccountActionPerformed
        if (accountInfoForm != null && accountInfoForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Account Info is already open!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (withdrawForm != null && withdrawForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Withdraw must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (depositForm != null && depositForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Deposit must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (balanceForm != null && balanceForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Balance must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        accountInfoForm = new AccountInfoForm(customer);
    }//GEN-LAST:event_btnViewAccountActionPerformed

    private void btnViewBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBalanceActionPerformed
        if (balanceForm != null && balanceForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Balance is already open!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (accountInfoForm != null && accountInfoForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Account Info must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (withdrawForm != null && withdrawForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Withdraw must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (depositForm != null && depositForm.isDisplayable()) {
            JOptionPane.showMessageDialog(null, "Deposit must be closed first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        balanceForm = new BalanceForm(customer);
    }//GEN-LAST:event_btnViewBalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BankForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewAccount;
    private javax.swing.JButton btnViewBalance;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
