/*

    Manapsal, Gabriel
    Llanes, Joshua
    Publico, Philip
    Riparip, Marc
    BSIT WMA 3B

*/

package com.mlpr.bankmanagementsystem;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class TransactionHistoryForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionHistoryForm.class.getName());

    private Customer customer;
    private Account account;
    
    /**
     * Creates new form TransactionHistoryForm
     */
    public TransactionHistoryForm(Customer customer) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Load icon
        try {
            URL iconUrl = getClass().getResource("/viewbalance.png");
            if (iconUrl != null) {
                setIconImage(new ImageIcon(iconUrl).getImage());
            } else {
                System.err.println("Icon not found at /viewbalance.png");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        this.customer = customer;
        if (customer != null) {
            this.account = customer.getAccount();
        }
        
        populateTransactionTable();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblLogo = new javax.swing.JLabel();
        lblTransactionHistory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Transaction History", "Amount", "Timestamp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankLogo6.png"))); // NOI18N

        lblTransactionHistory.setBackground(new java.awt.Color(255, 204, 0));
        lblTransactionHistory.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTransactionHistory.setForeground(new java.awt.Color(0, 154, 0));
        lblTransactionHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTransactionHistory.setText("Transaction History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lblLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTransactionHistory)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionHistoryForm(null).setVisible(true));
    }
    
    private void populateTransactionTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear existing rows

        if (account == null) {
            return;
        }

        List<String> transactions = account.getTransactionHistory();
        
        for (String transaction : transactions) {
            String[] parts = transaction.split("] ");
            String timestamp = parts[0].substring(1);
            String rest = parts[1];
            
            String transactionType;
            String amount;
            
            if (rest.startsWith("DEPOSIT")) {
                transactionType = "DEPOSIT";
                amount = rest.split("₱")[1].split(" \\|")[0];
            } else if (rest.startsWith("WITHDRAW")) {
                transactionType = "WITHDRAW";
                amount = rest.split("₱")[1].split(" \\|")[0];
            } else {
                transactionType = "Account Created";
                amount = "N/A";
            }
            
            model.addRow(new Object[]{
                transactionType,
                amount,
                timestamp
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTransactionHistory;
    // End of variables declaration//GEN-END:variables
}
